[package]
name = "rammingen_android"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rammingen = { path = "../../client" }

jni = { workspace = true }
tracing = { workspace = true }
