name: Checks

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash -e {0}

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.os }}
    steps:
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev
      - uses: ikalnytskyi/action-setup-postgres@v8
        with:
          postgres-version: 18
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
      - run: |
          cargo test --locked --all-targets --all-features
          DB_URL='postgresql://postgres:postgres@localhost:5432/postgres'
          cargo run --locked --release --bin rammingen_tests -- \
            --database-url "$DB_URL" \
            --seed 16962821275976580781 \
            snapshot
          psql "$DB_URL" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
          cargo run --locked --release --bin rammingen_tests -- \
            --database-url "$DB_URL" \
            --seed 4226198923619095502 \
            shuffle

  format:
    name: Check formatting
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
      - run: cargo fmt --check

  lint:
    name: Lint
    runs-on: ${{ inputs.os }}
    steps:
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
      - run: cargo clippy --locked --all-targets --all-features -- --deny warnings
